# Generated by Django 5.2.10 on 2026-01-29 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_ages', models.IntegerField()),
                ('max_ages', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(max_length=255)),
                ('sity', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carpet', models.IntegerField()),
                ('origin_title', models.TextField()),
                ('est_start_datetime', models.DateTimeField()),
                ('real_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('mark', models.FloatField(blank=True, null=True)),
                ('ages_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.agecategory')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.competition')),
                ('disciplines_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.disciplinecategory')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.participant')),
            ],
        ),
    ]
