# Generated by Django 5.2.10 on 2026-02-04 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_level', models.IntegerField(unique=True)),
                ('level_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('competitions_count', models.IntegerField(default=0)),
                ('performances_count', models.IntegerField(default=0)),
                ('gold_count', models.IntegerField(default=0)),
                ('silver_count', models.IntegerField(default=0)),
                ('bronze_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, unique=True)),
                ('participants_count', models.IntegerField(default=0)),
                ('competitions_count', models.IntegerField(default=0)),
                ('performances_count', models.IntegerField(default=0)),
                ('gold_count', models.IntegerField(default=0)),
                ('silver_count', models.IntegerField(default=0)),
                ('bronze_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('min_ages', models.IntegerField()),
                ('max_ages', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('min_ages', 'max_ages', 'sex'), name='unique_age_category')],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(max_length=255)),
                ('sity', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('competiton_active_status', models.TextField(blank=True, default='unknown')),
                ('regions_count', models.IntegerField(default=0)),
                ('participants_count', models.IntegerField(default=0)),
                ('performances_count', models.IntegerField(default=0)),
                ('gold_count', models.IntegerField(default=0)),
                ('silver_count', models.IntegerField(default=0)),
                ('bronze_count', models.IntegerField(default=0)),
                ('competition_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.competitionlevel')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceCarpet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carpet', models.IntegerField(default=1)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.competition')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceCategoryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants_count', models.IntegerField(default=0)),
                ('number_at_carpet', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, default='unknown', max_length=50)),
                ('age_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.agecategory')),
                ('discipline_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.disciplinecategory')),
                ('performance_category_carpet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.performancecarpet')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_title', models.TextField()),
                ('est_start_datetime', models.DateTimeField()),
                ('real_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('mark', models.FloatField(blank=True, null=True)),
                ('place', models.IntegerField(blank=True, null=True)),
                ('number_at_block', models.IntegerField(default=0)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.participant')),
                ('performance_category_block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.performancecategoryblock')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.regions'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='TrackedRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracked_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.regions')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TrackedParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracked_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.participant')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TrackedCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracked_competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.competition')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TrackedCategoryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracked_category_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.performancecategoryblock')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TrackedCarpet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracked_carpet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.performancecarpet')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.TextField(blank=True, help_text='Названия команд/городов через запятую')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
                ('telergam_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.userprofile')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.UniqueConstraint(fields=('name', 'sity', 'start_date', 'end_date'), name='unique_competition'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('name', 'region'), name='unique_participant'),
        ),
    ]
