# Generated by Django 5.2.10 on 2026-01-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='real_end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
