# Generated by Django 5.2.10 on 2026-02-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='place',
            field=models.IntegerField(blank=True, help_text='Занятое место (1, 2, 3...)', null=True),
        ),
    ]
