# Generated by Django 5.2.10 on 2026-02-01 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_performance_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, unique=True)),
                ('participants_count', models.IntegerField(default=0)),
                ('competitions_count', models.IntegerField(default=0)),
                ('performances_count', models.IntegerField(default=0)),
                ('gold_count', models.IntegerField(default=0)),
                ('silver_count', models.IntegerField(default=0)),
                ('bronze_count', models.IntegerField(default=0)),
                ('avg_score', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статистика региона',
                'verbose_name_plural': 'Статистика регионов',
            },
        ),
        migrations.CreateModel(
            name='AthleteStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitions_count', models.IntegerField(default=0)),
                ('performances_count', models.IntegerField(default=0)),
                ('gold_count', models.IntegerField(default=0)),
                ('silver_count', models.IntegerField(default=0)),
                ('bronze_count', models.IntegerField(default=0)),
                ('avg_score', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='main.participant')),
            ],
            options={
                'verbose_name': 'Статистика спортсмена',
                'verbose_name_plural': 'Статистика спортсменов',
            },
        ),
    ]
