# Generated by Django 5.2.10 on 2026-02-03 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_regionstatistics_athletestatistics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Токен входа Telegram',
                'verbose_name_plural': 'Токены входа Telegram',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('is_telegram_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('competition', 'Соревнование'), ('participant', 'Участник'), ('region', 'Команда/Регион'), ('category', 'Категория соревнования')], max_length=20)),
                ('competition_id', models.IntegerField(blank=True, help_text="ID соревнования для типа 'competition' и 'category'", null=True)),
                ('participant_id', models.IntegerField(blank=True, help_text="ID участника для типа 'participant'", null=True)),
                ('region_name', models.CharField(blank=True, help_text="Название региона для типа 'region'", max_length=100, null=True)),
                ('category_identifier', models.CharField(blank=True, help_text="Идентификатор категории для типа 'category'", max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='main.userprofile')),
            ],
            options={
                'verbose_name': 'Подписка на уведомления',
                'verbose_name_plural': 'Подписки на уведомления',
                'unique_together': {('user_profile', 'subscription_type', 'competition_id', 'participant_id', 'region_name', 'category_identifier')},
            },
        ),
    ]
